/**
 * Jeu d'icônes unique de l'application — Lucide (trait fin, moderne).
 * Réexporté sous les noms utilisés partout dans le code.
 */
export {
  LayoutDashboard as IconDashboard,
  ClipboardList as IconTasks,
  Building2 as IconDepartments,
  Users as IconUsers,
  UserRound as IconUser,
  Inbox as IconInbox,
  ChartColumnBig as IconReports,
  Settings as IconSettings,
  Menu as IconMenu,
  LogOut as IconLogout,
  Briefcase as IconBriefcase,
  SquarePen as IconEdit,
  Trash2 as IconTrash,
  Eye as IconEye,
  Power as IconPower,
  Bell as IconBell,
  Plus as IconPlus,
  X as IconX,
  Upload as IconUpload,
  FileText as IconFile,
  Clock as IconClock,
  Check as IconCheck,
  CheckCheck as IconCheckCheck,
  Download as IconDownload,
  ExternalLink as IconExternal,
  CircleCheck as IconCircleCheck,
  RotateCcw as IconReopen,
  TrendingUp as IconTrend,
  TriangleAlert as IconAlert,
  CircleCheckBig as IconDone,
  Timer as IconTimer,
  Star as IconStar,
  CalendarClock as IconCalendar,
  FolderKanban as IconProjects,
  Flag as IconMilestone,
  Link2 as IconDependency,
  Wallet as IconBudget,
  FolderOpen as IconDocuments,
} from 'lucide-react'
